;; cmd.c is the cheat sheet for this file

(defmacro defun-nethack-command (fun docstr cmdstr)
  "Define an interactive nethack command."
  `(defun ,(intern (concat "nethack-command-" (symbol-name fun))) (&optional count)
     ,docstr
     (interactive "p")
     (nethack-handle-command ,cmdstr count)))

(defun-nethack-command identify-trap "^       Show the type of a trap" "idtrap")
(defun-nethack-command apply "a       Apply (use) a tool" "apply")
(defun-nethack-command remove-all-armor "A       Remove all armor" "remarm")
(defun-nethack-command close-door "c       Close a door" "close")
(defun-nethack-command drop "d       Drop an item" "drop")
(defun-nethack-command drop-specific-item "D       Drop specific item types" "ddrop")
(defun-nethack-command kick "^D      Kick" "kick")
(defun-nethack-command eat "e       Eat something" "eat")
(defun-nethack-command engrave "E       Engrave writing on the floor" "engrave")
(defun-nethack-command fire "f       Fire ammunition from quiver" "fire")
(defun-nethack-command west "h       Go west 1 space" "gowest")
(defun-nethack-command west-until-ontop "H       Go west until you are on top of something" "gowestontop")
(defun-nethack-command west-until-near "^H      Go west until you are near something" "gowestnear")
(defun-nethack-command inventory "i       Show your inventory" "inv")
(defun-nethack-command type-inventory "I       Inventory specific item types" "typeinv")
(defun-nethack-command south "j       Go south 1 space (or if number_pad is on, jump to another location)" "gosouth")
(defun-nethack-command south-until-ontop "J       Go south until you are on top of something" "gosouthontop")
(defun-nethack-command south-until-near "^J      Go south until you are near something" "gosouthnear")
(defun-nethack-command north "k       Go north 1 space (or if number_pad is on, kick something)" "gonorth")
(defun-nethack-command north-until-ontop "K       Go north until you are on top of something" "gonorthontop")
(defun-nethack-command north-until-near "^K      Go north until you are near something" "gonorthnear")
(defun-nethack-command east "l       Go east 1 space (or if number_pad is on, loot a box on the floor)" "goeast")
(defun-nethack-command east-until-ontop "L       Go east until you are on top of something" "goeastontop")
(defun-nethack-command east-until-near "^L      Go east until you are near something" "goeastnear")
(defun-nethack-command southwest "b       Go southeast 1 space" "gosouthwest")
(defun-nethack-command southeast "n       Go southeast 1 space" "gosoutheast")
(defun-nethack-command southeast-until-ontop "N       Go southeast until you are on something (if number_pad, name an object)" "gosoutheastontop")
(defun-nethack-command southeast-until-near "^N      Go southeast until you are near something" "gosoutheastnear")
(defun-nethack-command open "o       Open a door" "open")
(defun-nethack-command settings "O       Show option settings, possibly change them" "set")
(defun-nethack-command pay "p       Pay your shopping bill" "pay")
(defun-nethack-command put-on "P       Put on an accessory (ring, amulet, etc)" "puton")
(defun-nethack-command quaff "q       Quaff (drink) something" "drink")
(defun-nethack-command select-ammo-for-quiver "Q       Select ammunition for quiver" "wieldquiver")
(defun-nethack-command read "r       Read a scroll or spellbook" "read")
(defun-nethack-command remove-accessory "R       Remove an accessory (ring, amulet, etc)" "remring")
(defun-nethack-command search "s       Search for traps and secret doors" "search")
(defun-nethack-command save-game "S       Save the game" "save")
(defun-nethack-command throw "t       Throw something" "throw")
(defun-nethack-command remove-single-armor "T       Take off one piece of armor" "takeoff")
(defun-nethack-command northeast "u       Go northeast 1 space (or if number_pad is on, untrap something)" "gonortheast")
(defun-nethack-command northeast-until-ontop "U       Go northeast until you are on top of something" "gonortheastontop")
(defun-nethack-command northeast-until-near "^U      Go northeast until you are near something" "gonortheastnear")
(defun-nethack-command version "v       Show version" "version")
(defun-nethack-command version-and-history "V       Show long version and game history" "history")
(defun-nethack-command wield "w       Wield (put in use) a weapon" "wield")
(defun-nethack-command wear-armor "W       Wear a piece of armor" "wear")
(defun-nethack-command swap-weapons "x       Swap wielded and secondary weapons" "swapweapon")
(defun-nethack-command explore-mode "X       Enter explore (discovery) mode (only if defined)" "enter_explore_mode")
(defun-nethack-command northwest "y       Go northwest 1 space" "gonorthwest")
(defun-nethack-command northwest-until-ontop "Y       Go northwest until you are on top of something" "gonorthwestontop")
(defun-nethack-command northwest-until-near "^Y      Go northwest until you are near something" "gonorthwestnear")
(defun-nethack-command zap-wand "z       Zap a wand" "zap")
(defun-nethack-command cast-spell "Z       Zap (cast) a spell" "cast")
(defun-nethack-command up "<       Go up a staircase" "up")
(defun-nethack-command down ">       Go down a staircase" "down")
(defun-nethack-command what-is-symbol "/       Show what type of thing a symbol corresponds to" "whatis")
(defun-nethack-command help "?       Give a help message" "help")
(defun-nethack-command command-help "&       Tell what a command does" "whatdoes")
(defun-nethack-command shell-escape "!       Do a shell escape (only if defined)" "sh")
(defun-nethack-command show-discoveries "\       Show what object types have been discovered" "discovered")
(defun-nethack-command rest-one-move ".       Rest one move while doing nothing" "null")
(defun-nethack-command look-here ":       Look at what is on the floor" "look")
(defun-nethack-command what-is-map-piece "; Show what type of thing a map symbol on the level corresponds to" "quickwhatis")
(defun-nethack-command pick-up ",       Pick up things at the current location" "pickup")
(defun-nethack-command toggle-pickup "@       Toggle the pickup option on/off" "togglepickup")
(defun-nethack-command show-all-equipment-in-use "*       Show all equipment in use (combination of the ),[,=,\",( commands)" "prinuse")
(defun-nethack-command count-gold "$       Count your gold" "countgold")
(defun-nethack-command list-known-spells "+       List known spells" "listspells")
;;; wizard (debug) mode only commands:
(defun-nethack-command wizard-search "^E      Search a room (available in debug mode only)" "wizardsearch")
(defun-nethack-command wizard-map "^F      Map the level (available in debug mode only)" "wizardmap")
(defun-nethack-command wizard-show-location "^O      Show location of special levels (available in debug mode only)" "wizardshowlocation")
(defun-nethack-command wizard-teleport-between-levels "^V      Teleport between levels (available in debug mode only)" "wizardteleportbetweenlevels")
(defun-nethack-command wizard-wish "^W      Wish (available in debug mode only)" "wizardwish")
;; Extended commands
(defun-nethack-command adjust "adjust inventory letters." "adjust")
(defun-nethack-command chat "talk to someone." "chat")
(defun-nethack-command conduct "list which challenges you have adhered to." "conduct")
(defun-nethack-command dip "dip an object into something." "dip")
(defun-nethack-command enhance "advance or check weapons skills." "enhance")
(defun-nethack-command force "force a lock." "force")
(defun-nethack-command invoke "invoke an object's powers." "invoke")
(defun-nethack-command jump "jump to a location." "jump")
(defun-nethack-command loot "loot a box on the floor." "loot")
(defun-nethack-command monster "use a monster's special ability." "monster")
(defun-nethack-command name "name an item or type of object." "name")
(defun-nethack-command offer "offer a sacrifice to the gods." "offer")
(defun-nethack-command pray "pray to the gods for help." "pray")
(defun-nethack-command quit "exit without saving current game." "quit")
(defun-nethack-command ride "ride (or stop riding) a monster." "ride")
(defun-nethack-command rub "rub a lamp." "rub")
(defun-nethack-command sit "sit down." "sit")
(defun-nethack-command turn "turn undead." "turn")
(defun-nethack-command twoweapon "toggle two-weapon combat." "twoweapon")
(defun-nethack-command untrap "untrap something." "untrap")
(defun-nethack-command version "list compile time options for this version of NetHack." "version")
(defun-nethack-command wipe "wipe off your face." "wipe")

;;; FIXME: defun these:
;; (defun-nethack-command redo-previous "^A      Redo the previous command" ???)
;; (defun-nethack-command create-monster "^G      Create a monster (available in debug mode only)" ???)
;; (defun-nethack-command identify-all-items "^I      Identify all items (available in debug mode only)" ???)
;; (defun-nethack-command previous-message "^P      Toggle through previously displayed game messages" ???)
;; (defun-nethack-command redraw-screen "^R      Redraw screen" ???)
;; (defun-nethack-command teleport-around-level "^T      Teleport around level" ???)
;; (defun-nethack-command suspend-game "^Z      Suspend game (only if defined)" ???)
;; (defun-nethack-command cancel "^[      Cancel command" ???)
;; (defun-nethack-command southwest-one-space "b       Go southwest 1 space" ???)
;; (defun-nethack-command southwest-until-ontop "B       Go southwest until you are on top of something" ???)
;; (defun-nethack-command southwest-until-near "^B      Go southwest until you are near something" ???)
;; (defun-nethack-command call-monster "C       Call (name) a particular monster" ???)
;; (defun-nethack-command force-fight "F       Followed by direction, fight a monster (even if you don't sense it)" ???)
;; (defun-nethack-command move-until-near "g       Followed by direction, move until you are near something" ???)
;; (defun-nethack-command move "G       Followed by direction, same as control-direction" ???)
;; (defun-nethack-command move-no-pickup-or-fight "m       Followed by direction, move without picking anything up or fighting" ???)
;; (defun-nethack-command move-distance-no-pickup "M       Followed by direction, move a distance without picking anything up" ???)
;; (defun-nethack-command show-wielded-weapon ")       Show the weapon currently wielded" ???)
;; (defun-nethack-command show-worn-armor "[       Show the armor currently worn" ???)
;; (defun-nethack-command show-worn-rings "=       Show the ring(s) currently worn" ???)
;; (defun-nethack-command show-worn-amulet "\"       Show the amulet currently worn" ???)
;; (defun-nethack-command show-tool-in-use "(       Show the tools currently in use" ???)

(provide 'nethack-cmd)
